### PR TITLE
partially fix issue #26

### PR DESCRIPTION
**Pull request by Daniel-Cortez**
Added checks to CASETBL and all of the jump opcodes in VerifyPcode and also to LREF.S.pri, LREF.S.alt, SREF.S, LREF.P.S.pri, LREF.P.S.alt, SREF.P.S, SCTRL, RET and RETN in amx_Exec.
I'm not 100% sure if the fix is correct, but I hope it will help.
Also these checks still need to be applied in the assembly cores, hence this fix is only partial.

### CODE REVIEW

**Comment by Daniel-Cortez** [comment]
Just checked the patch over and realized that I forgot to add multiple of cell size checks to SWITCH.OVL and RETN.OVL. Added them in the latest commit.
Also moved the check in SCTRL 5 to a point before setting the value in FRM. That way it makes more sense I guess.

**Comment by Y-Less** [comment]
OK, I literally JUST noticed that the same is true of almost all OpCodes in all versions, so really the bounds checks don't do much good at all...

**Comment by Daniel-Cortez** [comment]
@Y-Less I know that these bugs can be used for good reasons and I really admire the great job you did - almost every SA-MP gamemode uses at least one of your works.
Yes, using bugs and vulnerabilities seems to be acceptable in the SA-MP community due to a lot of unpatched bugs in 3.0/3.2 and the fact that SA-MP will never switch to Pawn 4 because it will break compatibility for all of the scripts/includes/libraries written in Pawn 3.2 (not mentioning the overall stagnation of SA-MP itself).
But if such hackish practice is normal for SA-MP, it doesn't mean it should be normal in all of the other projects that use Pawn 4. No matter what reasons vulnerabilities are abused for, good or bad, they are still vulnerabilities.


>This line:
>if (offs>=hea && offs<stk || (ucell)offs>=(ucell)amx->stp)
>Throws an error if the access is above the top of the stack

Isn't it how it's supposed to work?
STP marks the end of the stack/heap section and there are no other sections after it. In other words, access to an address after amx->stp ''is'' invalid.
And if the value in 'offs' is negative, '(ucell)offs' will give a huge unsigned value that will definitely be greater than STP.
That way the expression '(ucell)offs>=(ucell)amx->stp' combines two checks: if 'offs' ils less than 'amx->stp' and if 'offs' is not negative - such a neat optimization trick.

**Comment by Y-Less** [comment]
I wasn't saying they shouldn't be patched, hence why I was trying to help fix the patch, just saying that I didn't personally like it despite it being probably the right thing to do. However, you are right that the code isn't wrong - I didn't notice the `(ucell)` cast.

**Pull request closed without merging**
